development:
  adapter: postgresql
  database: dinner_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dinner_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dinner_production
  pool: 5
  timeout: 5000
